---
- hosts: all
  vars:
   - httpd_packages:
      - mod_wsgi
      - httpd
   - apache_test_message: 'http test'
  tasks:
       - name: "httpd_packages"
         yum: name={{ httpd_packages  }} state=latest
       - name: "apache_test_message"
         shell: echo {{ apache_test_message }} > /var/www/html/index.html
   handlers:
       - name: restart httpd
         service: name=httpd state=restarted enabled=yes
